name: continuous integration example

on:
  push:
    branches:
      main


jobs:
  build-and-test0please:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@vq

      - name: Install Java
        uses: action/setup-java@v1
        with:
          java-version: "11"

      - name: Build with gradle
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew build -x test

      - name: Run tests !!!
        working-directory: .
        run: |
          chmod +x gradlew
          ./gradlew test
